// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtjZNnXtrSn3JG4okMrfpA22Ar3jb8CPw',
    appId: '1:1053994590912:web:88b516389d14bd2f154325',
    messagingSenderId: '1053994590912',
    projectId: 'flutter-shopping-list-e4d43',
    authDomain: 'flutter-shopping-list-e4d43.firebaseapp.com',
    storageBucket: 'flutter-shopping-list-e4d43.appspot.com',
    measurementId: 'G-H8ZRZSQBMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_5zzlowUeDxMygT4ryn9OaJAlSUpICI',
    appId: '1:1053994590912:android:32eb1139236eebd6154325',
    messagingSenderId: '1053994590912',
    projectId: 'flutter-shopping-list-e4d43',
    storageBucket: 'flutter-shopping-list-e4d43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsGTuj9uNc2RNtzzX0hYqQReztG0UR4E',
    appId: '1:1053994590912:ios:242662c6570cd2ea154325',
    messagingSenderId: '1053994590912',
    projectId: 'flutter-shopping-list-e4d43',
    storageBucket: 'flutter-shopping-list-e4d43.appspot.com',
    iosClientId: '1053994590912-curqkhvi7di2b2pc6u7besk0t24c8um9.apps.googleusercontent.com',
    iosBundleId: 'flutter-shopping-list',
  );
}
