// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtjZNnXtrSn3JG4okMrfpA22Ar3jb8CPw',
    appId: '1:1053994590912:web:88b516389d14bd2f154325',
    messagingSenderId: '1053994590912',
    projectId: 'flutter-shopping-list-e4d43',
    authDomain: 'flutter-shopping-list-e4d43.firebaseapp.com',
    storageBucket: 'flutter-shopping-list-e4d43.appspot.com',
    measurementId: 'G-H8ZRZSQBMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_5zzlowUeDxMygT4ryn9OaJAlSUpICI',
    appId: '1:1053994590912:android:32eb1139236eebd6154325',
    messagingSenderId: '1053994590912',
    projectId: 'flutter-shopping-list-e4d43',
    storageBucket: 'flutter-shopping-list-e4d43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsGTuj9uNc2RNtzzX0hYqQReztG0UR4E',
    appId: '1:1053994590912:ios:6285d683d7759dca154325',
    messagingSenderId: '1053994590912',
    projectId: 'flutter-shopping-list-e4d43',
    storageBucket: 'flutter-shopping-list-e4d43.appspot.com',
    iosClientId: '1053994590912-b9hpt5jl3i7idmv28b6gf5qg5kn205k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterShoppingList',
  );
}
